### ISSUE TITLE
huts broke in mp2

### ISSUE THREAD

**Issue by Canik05** [Canik05/freeciv-tnt#3]
The site when up while Freeciv was undergoing code changes. While trying to figure them out (along with everything else starting a new site entails) I either broke huts or failed to include some change. 

The huts still seem to work in civ2civ3 but not in ag, mp2-brava. I tried changing the lua.scripts but so far no luck. plz help :D

**Comment by cazfi** [comment]
> The huts still seem to work in civ2civ3 but not in ag, mp2-brava. I tried changing the lua.scripts but so far no luck. plz help :D

Compare default.lua those rulesets ship themselves (for some reason) with the default default.lua that civ2civ3 uses.
It could also help to go through descriptions of the pull requests and commit messages I wrote when doing updates for the server of FCW. I remember there being some change(s) to hut scripting API.

**Comment by cazfi** [comment]
Actually the problem (reading mp2-brava files, at least) is that terrain.ruleset has not been updated for the introduction of extra rmcause "Enter".

**Comment by Canik05** [comment]
ok, I see.

`[extra_hut]
name           = _("Minor Tribe Village")
rule_name      = "Hut"
category       = "Bonus"
causes         = "Hut"
rmcauses       = "Enter"
`
(rmcauses with commented out)

I think I did fix that part at one point but the hut rewards was not set up properly and my work & brain got all jumbled with so many issues. I can probably sort it out now, thank you. :)

**Comment by Canik05** [comment]
or maybe not. 
even when I copied fcw's /data/ag/default.lua and even when I removed the tech section it continues to give tech as a random reward hmm.

**Comment by cazfi** [comment]
> or maybe not. even when I copied fcw's /data/ag/default.lua and even when I removed the tech section it continues to give tech as a random reward hmm.
First possible explanation that comes to my mind is that you may have accidentally introduced an error to the ruleset that makes it not to load, but causes server to keep on using previous or default ruleset, that has the tech reward from huts enabled. Does it say that it has loaded the ruleset succesfully?

**Comment by Canik05** [comment]
the ruleset does load successfully, yes. it's _not_ being reverted back to classic due to a failed ruleset load. I'm noob but not that noob. :)

**Comment by Canik05** [comment]
sorry, should work now.

https://github.com/Canik05/freeciv-tnt/commit/c1dd6fb795a761ebb86f3bf7464b26c39a878540

**Comment by cazfi** [comment]
Required also adding some extra styles to amplio2.tilespec, but I've run a couple of games now. Set huts to max, and have entered dozens of them, always getting either small amount of gold or rarely mercenaries.

**Comment by cazfi** [comment]
Oh, Makefile.am for those rulesets do not list default.lua as a file to install. So it will not be in place in installation directory, so default default.lua will be used.

**Comment by Canik05** [comment]
ah that's probably it then, ty

**Comment by Canik05** [comment]
yep. I tested and that fixed it! thanks Cazfi!
