### ISSUE TITLE
Action_Odds_Pct sanity checking 

### ISSUE THREAD

**Issue by Canik05** [Canik05/freeciv-tnt#35]
https://github.com/Canik05/freeciv-tnt/pull/29/commits/2045f117d773c324d3beed2c26120ad317f35fb1

^ this new sanity check causes load failure in MP2 rulesets.

Unfortunately I think I squash merged that commit. 
(I've since been told since I shouldn't squash server updates and now I see why.)

I'm not sure how to revert this change. Should I just remove it manually? 
At least temporarily I'll be removing it in my actual server build. 
I have to for MP2 rulesets to work.

@cazfi

**Comment by cazfi** [comment]
I can't look at the issue just now, but if the sanity check is finding an error in the ruleset, presumably it's the ruleset error that you should be fixing and not removing the error detection. Unless the error detection is faulty and claiming valid construct to be invalid, of course.

**Comment by cazfi** [comment]
The ruleset fix is probably just to completely remove the effects that the sanity check finds to be ineffective anyway.

**Comment by Canik05** [comment]
Ok, I'll take another look at it. Thanks

**Comment by Canik05** [comment]
I'm just going to leave this out of my current update (that I plan to do tomorrow). 

but it will be in the next one along with the required ruleset changes.

**Comment by kvilhaugsvik** [comment]
I think the problem is that the list of actions with a pre action dice roll that is correct for upstream was back ported without adding the actions downstream has added a dice roll to. This check uses that list.

**Comment by cazfi** [comment]
Right. So currently downstreams don't have the dice roll for some actions for which they expect to have it. (This sanity check is right in the sense that it's consistent with what the other code supports)

**Comment by cazfi** [comment]
Unless someone else is quicker, I'll submit a fix later tonight.

**Comment by Canik05** [comment]
Thanks to both of you. ❤️ 

I will close the issue once I've tested it.
